config/routes.rb
Rails.application.routes.draw do
  resources :problems do
  end
  resources :problem_issue
  resources :processareas

  resources :lineups

  get "/c/:location/:machine_code" => "complaints#show", as: :indiv_show_complaint
  get "/complaints/all" => "complaints#all"
 get "/pages/:page" => "pages#show"
  

  resources :images
  resources :complaints
  get 'a/image_management' => 'images#manindex', as: :image_management

  get "/api/get_images" => 'images#get_images', as: :get_images_json

  devise_for :users

  post "/api/login" => 'json_sessions#create'
  delete "/api/logout" => 'json_sessions#destroy'

  match "issues", to: "issues#index", via: [:options]
  match "issues/:issue_id/issue_workarounds/:id", to: "issue_workarounds#cors", via: [:options]

  root :to => 'issues#index'

  get "/about" => 'static_pages#about', as: :static_about
  get "/why" => 'static_pages#why', as: :static_why
  get "/products" => 'static_pages#products', as: :static_products

  get "/home" => 'static_pages#home', as: :home
  get '/layout' => 'layouts_show#show', as: :layouts_show

  get 'assignment/show/:role_id' => 'assignments#show', as: :assignment_role_view

  namespace :jobs do
    resources :jobs
    resources :steps
  end

  scope "/admin" do
    get "/", to: "admin#index", as: "admin_index"
    get "users", to: "admin#users", as: "admin_user_static"

    get "business", to: 'admin_business#edit', as: "business_edit"
    put "businesses/:id(.:format)", to: "admin_business#update", as: "business_update"

    get "depareas/departments", to: "admin#departments", as: "admin_departments_static"
    get "depareas/areas", to: "admin#areas", as: "admin_areas_static"
    get "depareas/department_areas", to: "admin#department_areas", as: "admin_department_areas_static"
    resources :users, only: [:new, :create, :update, :destroy, :edit, :show]

    resources :admin

    resources :issue_management do
      get 'view', as: :view
      member do
        get 'show_workarounds', as: :show_workarounds
        get 'show_solutions', as: :show_solutions
        get 'show_steps', as: :show_steps

        

      end
      resources :issue_workarounds, controller: 'review_management', type: 'IssueWorkaround', u: 'workaround'
      resources :solutions, controller: 'review_management', type: 'Solution', u: 'solutions'
    end

    resources :department_areas do
      resources :locations
    end

    resources :departments
    resources :areas
    resources :department_areas
    resources :impacts
  end

  get '/profile' => 'users#profile', as: :profile

  resources :businesses do
    member do
      get 'newly_created', as: :newly_created
    end
  end

 

  

  get "/activities" => "notifications#activity_feed", as: :activity_feed
  get "/notifications" => "notifications#notification", as: :notification_feed

  get '/issues/search' => "issues#search", as: :issue_search
  get 'search_results' => "issues#search_results", as: :search_results

  resources :issues do
    member do
      get 'show_workarounds' => "reviews#index", type: 'IssueWorkaround', u: 'workarounds', as: :show_workarounds
      get 'show_solutions' => "reviews#index", type: 'Solution', u: 'solutions', as: :show_solutions
      get 'show_steps' => "detailed_steps#index", as: :show_steps
      get 'show_images', as: :show_images
      get 'history', as: :history
      get 'draft_to_review', as: :draft_to_review
      get 'review_to_draft', as: :review_to_draft
      get 'review_to_publish', as: :review_to_publish
      get 'publish_to_review', as: :publish_to_review
      get 'publish_to_draft', as: :publish_to_draft
      get 'edit/images' => "issues#edit_images", as: :edit_images
      get 'edit/workarounds' => "issues#edit_workaround", as: :edit_workaround
      get 'edit/solutions' => "issues#edit_solutions", as: :edit_solutions
      get 'edit/attempted_solutions' => "issues#edit_attempted_solutions", as: :edit_attempted_solutions
    end
    resources :detailed_steps do
      collection do
        post 'step_number_update'
        get 'quick_show'
      end
    end
    resources :notes do
      post 'mark_as_checked', as: :marked_as_checked
      post 'mark_as_user_read', as: :mark_as_user_read
    end
    resources :records, only: [:create, :index, :new]
    resources :solutions, controller: 'reviews', type: 'Solution', u: 'solutions' do
    end
    resources :issue_workarounds, controller: 'reviews', type: 'IssueWorkaround', u: 'workarounds' do
    end
  end

  resources :media, only: [:show, :new, :create, :destroy]

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

	def index
		@business = Business.all
	end

	def new
		if !user_signed_in?
			@business = Business.new
		else
			redirect_to home_path
		end
	end

	def newly_created
		business = current_user.business

		dep = business.departments.count
		deparea = business.department_areas.count
		area = business.areas.count
		impact = business.impacts.count
		if dep == 0 or deparea == 0 or area == 0 or impact == 0
			render layout: "admin_layout"
		else
			flash[:admin_notice] = 'Business all ready set up'
			redirect_to admin_index_path
		end
	end

	def show
		@business = Business.find(params[:id])
	end

	def create

		@business = Business.new(business_params)
		@business.users.build(user_params)
		# sets the user that creates the business as the creator
		@business.users.first.creator = true
		@business.roles.build(name: "admin")
		@business.assignments.build(user: @business.users.first, role: @business.roles.first)
		# need to build/create the grants for the business

		Right.all.each do |right|
			Grant.create(right: right, role: @business.roles.first)
		end


		@business.intro = false

		respond_to do |format|
			if @business.save
				sign_in(:user, @business.users.first)
				format.html {redirect_to newly_created_business_path(@business)}
			else
				format.html {render action: 'new'}
			end
		end
	end

	private

	def business_params
		params.require(:business).permit(:name, :location)
	end

	def user_params
		params.require(:user).permit(:email, :password, :password, :name)
	end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%if @business.errors.any? %>
	<div id='error_explanation'>
		<h2><%= pluralize(@business.errors.count, "error") %> prohibited this issue from being saved</h2>

		<ul>
			<% @business.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%if @business.users.any? and @business.users.first.errors.any? %>
	<div id='error_explanation'>
		<h2><%= pluralize(@business.users.first.errors.count, "error") %> prohibited this issue from being saved</h2>

		<ul>
			<% @business.users.first.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class='form-group'>
	<label class='col-sm-3 control-label'>Business Name</label>
	<div class='col-sm-9'>
		<%= form.text_field :name, class: 'form-control' %>
	</div>
</div>

<div class='form-group'>
	<label class='col-sm-3 control-label'>Name</label>
	<div class='col-sm-9'>
		<%= text_field_tag 'user[name]', nil, { class: 'form-control' } %>
	</div> 
</div>

<div class='form-group'>
	<label class='col-sm-3 control-label'>User Email</label>
	<div class='col-sm-9'>
		<%= text_field_tag 'user[email]', nil, { class: 'form-control' } %>
	</div>
</div>

<div class='form-group'>
	<label class='col-sm-3 control-label'>Password</label>
	<div class='col-sm-9'>
		<%= password_field_tag 'user[password]', nil, { class: 'form-control' } %>
	</div>
</div>
<div class='form-group'>
	<label class='col-sm-3 control-label'>Password Confirmation</label>
	<div class='col-sm-9'>
		<%= password_field_tag 'user[password_confirmation]', nil, { class: 'form-control' } %>
	</div>
</div>


<div class='form-group'>
	<div class='col-sm-offset-3 col-sm-9'>
		<%= form.submit "Save", class: 'btn btn-default' %>
	</div>
</div>

app/views/businesses/index.html.erb
<h1>All Businesses Listed</h1>

<% @business.each do |business| %>
	<p>
		<span>Business : <%= business.name %></span>
		<span>Location : <%= business.location %></span>
	</p>
<% end %>

app/views/businesses/new.html.erb
<% content_for :title do %>
	Create an Account
<% end %>

<h3>Create an Account</h3>

<%= form_for @business, :html => {class: "form-horizontal"} do |form| %>
	<%= render partial: form %>
<% end %>

app/views/businesses/newly_created.html.erb
<% content_for :title do %>
	Newly Created Info
<% end %>

<h3>Newly Created Info</h3> 

<p>Congratuations on creating an account. Before you can go ahead and create issues or procedures, you first must set-up the business. First you must create departments, areas, assign those areas to the departments and set up the impacts that the issues will have</p>

<p>Below are some quick links to get you started</p>

<ol>
	<li><%= link_to "Departments", departments_path %></li>
	<li><%= link_to "Areas", areas_path %></li>
	<li><%= link_to "Departments Area's", department_areas_path %></li>
	<li><%= link_to "Impacts", impacts_path %></li>
</ol>

app/views/businesses/show.html.erb
<h1>Show Business</h1>


<p>Name : <%= @business.name %></p>

<p>Location : <%= @business.location %></p>