config/routes.rb
Rails.application.routes.draw do
  resources :problems do
  end
  resources :problem_issue
  resources :processareas

  resources :lineups

  get "/c/:location/:machine_code" => "complaints#show", as: :indiv_show_complaint
  get "/complaints/all" => "complaints#all"
 get "/pages/:page" => "pages#show"
  

  resources :images
  resources :complaints
  get 'a/image_management' => 'images#manindex', as: :image_management

  get "/api/get_images" => 'images#get_images', as: :get_images_json

  devise_for :users

  post "/api/login" => 'json_sessions#create'
  delete "/api/logout" => 'json_sessions#destroy'

  match "issues", to: "issues#index", via: [:options]
  match "issues/:issue_id/issue_workarounds/:id", to: "issue_workarounds#cors", via: [:options]

  root :to => 'issues#index'

  get "/about" => 'static_pages#about', as: :static_about
  get "/why" => 'static_pages#why', as: :static_why
  get "/products" => 'static_pages#products', as: :static_products

  get "/home" => 'static_pages#home', as: :home
  get '/layout' => 'layouts_show#show', as: :layouts_show

  get 'assignment/show/:role_id' => 'assignments#show', as: :assignment_role_view

  namespace :jobs do
    resources :jobs
    resources :steps
  end

  scope "/admin" do
    get "/", to: "admin#index", as: "admin_index"
    get "users", to: "admin#users", as: "admin_user_static"

    get "business", to: 'admin_business#edit', as: "business_edit"
    put "businesses/:id(.:format)", to: "admin_business#update", as: "business_update"

    get "depareas/departments", to: "admin#departments", as: "admin_departments_static"
    get "depareas/areas", to: "admin#areas", as: "admin_areas_static"
    get "depareas/department_areas", to: "admin#department_areas", as: "admin_department_areas_static"
    resources :users, only: [:new, :create, :update, :destroy, :edit, :show]

    resources :admin

    resources :issue_management do
      get 'view', as: :view
      member do
        get 'show_workarounds', as: :show_workarounds
        get 'show_solutions', as: :show_solutions
        get 'show_steps', as: :show_steps

        

      end
      resources :issue_workarounds, controller: 'review_management', type: 'IssueWorkaround', u: 'workaround'
      resources :solutions, controller: 'review_management', type: 'Solution', u: 'solutions'
    end

    resources :department_areas do
      resources :locations
    end

    resources :departments
    resources :areas
    resources :department_areas
    resources :impacts
  end

  get '/profile' => 'users#profile', as: :profile

  resources :businesses do
    member do
      get 'newly_created', as: :newly_created
    end
  end

 

  

  get "/activities" => "notifications#activity_feed", as: :activity_feed
  get "/notifications" => "notifications#notification", as: :notification_feed

  get '/issues/search' => "issues#search", as: :issue_search
  get 'search_results' => "issues#search_results", as: :search_results

  resources :issues do
    member do
      get 'show_workarounds' => "reviews#index", type: 'IssueWorkaround', u: 'workarounds', as: :show_workarounds
      get 'show_solutions' => "reviews#index", type: 'Solution', u: 'solutions', as: :show_solutions
      get 'show_steps' => "detailed_steps#index", as: :show_steps
      get 'show_images', as: :show_images
      get 'history', as: :history
      get 'draft_to_review', as: :draft_to_review
      get 'review_to_draft', as: :review_to_draft
      get 'review_to_publish', as: :review_to_publish
      get 'publish_to_review', as: :publish_to_review
      get 'publish_to_draft', as: :publish_to_draft
      get 'edit/images' => "issues#edit_images", as: :edit_images
      get 'edit/workarounds' => "issues#edit_workaround", as: :edit_workaround
      get 'edit/solutions' => "issues#edit_solutions", as: :edit_solutions
      get 'edit/attempted_solutions' => "issues#edit_attempted_solutions", as: :edit_attempted_solutions
    end
    resources :detailed_steps do
      collection do
        post 'step_number_update'
        get 'quick_show'
      end
    end
    resources :notes do
      post 'mark_as_checked', as: :marked_as_checked
      post 'mark_as_user_read', as: :mark_as_user_read
    end
    resources :records, only: [:create, :index, :new]
    resources :solutions, controller: 'reviews', type: 'Solution', u: 'solutions' do
    end
    resources :issue_workarounds, controller: 'reviews', type: 'IssueWorkaround', u: 'workarounds' do
    end
  end

  resources :media, only: [:show, :new, :create, :destroy]

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :issue
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		@issue = Issue.find(params[:issue_id])
		@notes = @issue.notes.all
	end

	def show

	end

	def new
		@issue = Issue.find(params[:issue_id])
		@note = @issue.notes.new
	end

	def create
		@issue = Issue.find(params[:issue_id])
		@note = @issue.notes.new(note_params)

		@note.version_number = @issue.versions.length
		@note.checked = false
		@note.author_read = false

		@note.save
		redirect_to issue_notes_path(@issue)
	end

	def edit

	end

	def update

	end

	def mark_as_checked
		@issue = Issue.find(params[:issue_id])
		@note = @issue.notes.find(params[:note_id])

		@note.checked = true
		@note.save
		redirect_to issue_notes_path(@issue)
	end

	def mark_as_user_read
		@issue = Issue.find(params[:issue_id])
		@note = @issue.notes.find(params[:note_id])
		if current_user.id == @issue.user_id
			@note.author_read = true
			@note.save
		else
			return redirect_to issue_notes_path(@issue), notice: "User is not the author id, cannot mark as read"
		end

		redirect_to edit_issue_path(@issue)
	end

	private

	def note_params
		params.require(:note).permit(:context, :category)
	end
end

app/views/notes/_form.html.erb
<%if @note.errors.any? %>
	<div id='error_explanation'>
		<h2><%= pluralize(@note.errors.count, "error") %> prohibited this issue from being saved</h2>

		<ul>
			<% @note.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form.label :context %>
<%= form.text_area :context %>
<br>
<%= form.label :category %>
<%= form.text_field :category %>

<%= form.submit "Save" %>

app/views/notes/edit.html.erb
<%= form_for @note do |form| %>
	<%= render partial: form %>
<% end %>

app/views/notes/index.html.erb
<h3>Notes Index</h3>
<div class="panel-group" id="accordion">

	<% @notes.each do |note| %>

	  <div class="panel panel-default">
	    <div class="panel-heading">
	      <h4 class="panel-title">
	        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= note.id %>">
	          <%= format_date_time note.created_at %>
	        </a>
	      </h4>
	    </div>
	    <div id="collapse<%= note.id %>" class="panel-collapse collapse in">
	      <div class="panel-body">
				<ul class="list-group">
				  <li class="list-group-item">Message : <%= note.context %></li>
				  <li class="list-group-item">Category : <%= note.category %></li>
				  <li class="list-group-item">Checked : <%= note.checked %></li>
				  <li class="list-group-item">Note for Message : <%= note.version_number %></li>
				  <li class="list-group-item">Author Read : <%= note.author_read %></li>
				  <li class="list-group-item">
				  	<div class="btn-group">
						  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
						    Actions <span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" role="menu">
						  	<% if note.author_read == false && current_user.id == @issue.user_id %>
								<li><%= link_to "Acknoledge", issue_note_mark_as_user_read_path(@issue, note), method: :post %></li>
							<%  end %>
						  	<% if !note.checked %>
								<li><%= link_to "Mark as Checked", issue_note_marked_as_checked_path(@issue, note), method: :post %></li>
							<% end %>
						  </ul>
						</div>
				  </li>

				<ul>
	      </div>
	    </div>
	  </div>

	  <% end %>
</div>

<div class='row'>
	<div class="btn-group btn-group-justified">
		<%= link_to "Back", :back, class: "btn btn-default" %>
		<%= link_to "View", issue_path(@issue), class: "btn btn-default" %>
		<%= link_to "Edit", edit_issue_path(@issue), class: 'btn btn-default' %>
		<%= link_to "View All Issues", issues_path, class: 'btn btn-default' %>
	</div>
</div>

app/views/notes/new.html.erb
<%= form_for [@issue, @note] do |form| %>
	<%= render partial: form %>
<% end %>