config/routes.rb
Rails.application.routes.draw do
  resources :problems do
  end
  resources :problem_issue
  resources :processareas

  resources :lineups

  get "/c/:location/:machine_code" => "complaints#show", as: :indiv_show_complaint
  get "/complaints/all" => "complaints#all"
 get "/pages/:page" => "pages#show"
  

  resources :images
  resources :complaints
  get 'a/image_management' => 'images#manindex', as: :image_management

  get "/api/get_images" => 'images#get_images', as: :get_images_json

  devise_for :users

  post "/api/login" => 'json_sessions#create'
  delete "/api/logout" => 'json_sessions#destroy'

  match "issues", to: "issues#index", via: [:options]
  match "issues/:issue_id/issue_workarounds/:id", to: "issue_workarounds#cors", via: [:options]

  root :to => 'issues#index'

  get "/about" => 'static_pages#about', as: :static_about
  get "/why" => 'static_pages#why', as: :static_why
  get "/products" => 'static_pages#products', as: :static_products

  get "/home" => 'static_pages#home', as: :home
  get '/layout' => 'layouts_show#show', as: :layouts_show

  get 'assignment/show/:role_id' => 'assignments#show', as: :assignment_role_view

  namespace :jobs do
    resources :jobs
    resources :steps
  end

  scope "/admin" do
    get "/", to: "admin#index", as: "admin_index"
    get "users", to: "admin#users", as: "admin_user_static"

    get "business", to: 'admin_business#edit', as: "business_edit"
    put "businesses/:id(.:format)", to: "admin_business#update", as: "business_update"

    get "depareas/departments", to: "admin#departments", as: "admin_departments_static"
    get "depareas/areas", to: "admin#areas", as: "admin_areas_static"
    get "depareas/department_areas", to: "admin#department_areas", as: "admin_department_areas_static"
    resources :users, only: [:new, :create, :update, :destroy, :edit, :show]

    resources :admin

    resources :issue_management do
      get 'view', as: :view
      member do
        get 'show_workarounds', as: :show_workarounds
        get 'show_solutions', as: :show_solutions
        get 'show_steps', as: :show_steps

        

      end
      resources :issue_workarounds, controller: 'review_management', type: 'IssueWorkaround', u: 'workaround'
      resources :solutions, controller: 'review_management', type: 'Solution', u: 'solutions'
    end

    resources :department_areas do
      resources :locations
    end

    resources :departments
    resources :areas
    resources :department_areas
    resources :impacts
  end

  get '/profile' => 'users#profile', as: :profile

  resources :businesses do
    member do
      get 'newly_created', as: :newly_created
    end
  end

 

  

  get "/activities" => "notifications#activity_feed", as: :activity_feed
  get "/notifications" => "notifications#notification", as: :notification_feed

  get '/issues/search' => "issues#search", as: :issue_search
  get 'search_results' => "issues#search_results", as: :search_results

  resources :issues do
    member do
      get 'show_workarounds' => "reviews#index", type: 'IssueWorkaround', u: 'workarounds', as: :show_workarounds
      get 'show_solutions' => "reviews#index", type: 'Solution', u: 'solutions', as: :show_solutions
      get 'show_steps' => "detailed_steps#index", as: :show_steps
      get 'show_images', as: :show_images
      get 'history', as: :history
      get 'draft_to_review', as: :draft_to_review
      get 'review_to_draft', as: :review_to_draft
      get 'review_to_publish', as: :review_to_publish
      get 'publish_to_review', as: :publish_to_review
      get 'publish_to_draft', as: :publish_to_draft
      get 'edit/images' => "issues#edit_images", as: :edit_images
      get 'edit/workarounds' => "issues#edit_workaround", as: :edit_workaround
      get 'edit/solutions' => "issues#edit_solutions", as: :edit_solutions
      get 'edit/attempted_solutions' => "issues#edit_attempted_solutions", as: :edit_attempted_solutions
    end
    resources :detailed_steps do
      collection do
        post 'step_number_update'
        get 'quick_show'
      end
    end
    resources :notes do
      post 'mark_as_checked', as: :marked_as_checked
      post 'mark_as_user_read', as: :mark_as_user_read
    end
    resources :records, only: [:create, :index, :new]
    resources :solutions, controller: 'reviews', type: 'Solution', u: 'solutions' do
    end
    resources :issue_workarounds, controller: 'reviews', type: 'IssueWorkaround', u: 'workarounds' do
    end
  end

  resources :media, only: [:show, :new, :create, :destroy]

end

app/controllers/issue_management_controller.rb
class IssueManagementController < BIssueController

	authorize_resource class: false

	# before_action :check_intro
	# before_action :get_dep_area, only: [:new, :create, :edit,:edit_images, :edit_basic, :edit_workaround, :edit_solutions, :edit_attempted_solutions]
	# before_action :get_impacts, only: [:new, :create, :edit, :edit_images, :edit_basic, :edit_workaround, :edit_solutions, :edit_attempted_solutions]

	def index
		@issues = scoped.issues.page(params[:page])
		render layout: "admin_layout"
	end

	def show
		# @issue = scoped.issues.find(params[:id])
		super
		render layout: "admin_layout"
	end

	def view
		@active_workarounds = true
		@issue = scoped.issues.find(params[:issue_management_id])
		@list = scoped.issues.find(@issue).issue_workarounds
		@steps = @issue.detailed_steps
		# render layout: "show_issue_admin"
		render layout: "layouts/show_issue_admin", partial: "issues/show_review_table", locals: {list: @list}
	end

	def new
		super
		render layout: "admin_layout"
	end

	def create
		super
		respond_to do |format|
			if @issue.save
				flash[:admin_notice] = "Issue was created successfully"
				format.html { redirect_to issue_management_path(@issue) }
			else
				flash.now[:admin_alert] = "Issue is not valid"
				format.html {render action: 'new'}
			end
		end
	end

	def edit
		super
		render layout: "admin_layout"
	end

	def update
		super
		respond_to do |format|
			if @issue.update(issue_params)
				flash[:admin_notice] = "Issue was updated successfully"
				# format.html { redirect_to issue_management_view_path(@issue) }
				format.html { redirect_to issue_management_path(@issue) }
			else
				flash.now[:admin_alert] = "Issue is not valid"
				format.html {render action: 'edit' }
			end
		end
	end

	def destroy
		flash["admin_notice"] = "Issue has been destroyed"
		redirect_to issue_management_index_path
	end

	def edit_workaround
		# @active_workarounds = true
		# @workarounds = return_array @issue.issue_workarounds.includes(:images)
		super
		# Below lines are tempory to get everything up and running
		@admin = true
		@workaround_create = true


		render layout: "admin_layout", template: "issues/edit_workaround"
	end

	def edit_solutions
		# @active_solutions = true
		# @solutions = return_array @issue.solutions.includes(:images)
		super
		@solution_create = true
		@admin = true
		# render layout: "admin_layout", template: "issues/edit_solutions"
		# render layout: "admin_layout", template: "issues/show_review_table"
		render layout: "admin_layout", template: "issues/edit_solutions"
	end

	def show_workarounds
		@active_workarounds = true
		@name = 'workarounds'
		@list = @issue.issue_workarounds
		render layout: "layouts/show_issue_admin", partial: "issues/show_review_table", locals: {list: @list}
	end

	def show_solutions
		@active_solutions = true
		@name = 'solutions'
		@list = @issue.solutions
		# render layout: "show_issue_admin", template: "issues/show_solutions"
		render partial: "issues/show_review_table", layout: 'layouts/show_issue_admin', locals: {list: @list}
	end

	def show_steps
		@active_steps = true
		
		@issue = Issue.find(params[:id])
		@list = @issue.detailed_steps
		@steps = @issue.detailed_steps
		render partial: "issues/show_step_table", layout: 'layouts/show_issue_admin', locals: {list: @list}
	end

	private

	# def get_dep_area
	# 	@depAreas = DepartmentArea.all.includes(:department, :area)
	# end

	# def get_impacts
	# 	@impacts = Impact.all
	# end

	def issue_params
		params.require(:issue).permit(:name, :description, :impact_id, :department_area_id, :review_date, :picture ,:i_type, :preferences => [:howTo, :workaround, :solution])
	end


	# def scoped
	# 	current_user.business.issues
	# end
end

app/helpers/issue_management_helper.rb
module IssueManagementHelper
end

app/views/issue_management/edit.html.erb
<% content_for :title do %>
	Edit Issue
<% end %>

<% content_for :breadcrumb do %>
	<li><%= link_to "Issue Management", issue_management_index_path %></li>
	<li><%= link_to @issue.id, issue_management_view_path(@issue.id) %></li>
	<li class='active'>Edit</li>
<% end %>

<h3>Edit Issue Information</h3>

<%= form_for @issue, url: {controller: "issue_management", action: :update}, builder: MyFormBuilder, :html => { :multipart => true, class: "form-horizontal" } do |form| %>
		<%= render partial: 'issues/form', locals: {form: form} %>
<% end %> 

app/views/issue_management/index.html.erb
<% content_for :title do %>
	Issue Management
<% end %>

<% content_for :breadcrumb do %>
	<li class='active'>Issue Management</li>
<% end %>

<div class='row'>
	<div class='col-sm-12'><h4>Issue Management</h4></div>
</div>

<div class='row'>
	<div class='col-xs-10 col-sm-8'>
		<p>
		For an administrator keeping track of the issues are an absolutlty must. The ability to create, but also review and edit issues is a must have. From this page you can do exactly this. As an added bonus an issue will hightlight red when it is time for a reivew.
		</p>
	</div>
	<div class='col-xs-2 col-sm-4'>
		<%= link_to "Add an Issue", new_issue_management_path, class: "btn btn-default wrap_button" %>
	</div>
</div>

<div class='row'>
	<div class='col-sm-12'>
		<table class='table'>
			<tr>
				<th>Issue Name</th>
				<th>Department</th>
				<th>Area</th>
				<th class='hidden-xs'>Review Date</th>
			</tr>
			<% @issues.each do |issue| %>
				<% if issue.review_date < Time.now %>
					<tr class='danger'>
				<% else %>
					<tr>
				<% end %>
				<td><%= link_to issue.name, issue_management_path(issue) %></td>
				<td><%= issue.department_area.department.name %></td>
				<td><%= issue.department_area.area.name %></td>
				<td class='hidden-xs'><%= issue.review_date %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

<div class='row'>
	<div class='col-sm-12'>
		<%= will_paginate @issues, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/issue_management/new.html.erb
<% content_for :breadcrumb do %>
	<li><%= link_to "Issue Management", issue_management_index_path %></li>
	<li class='active'>New</li>
<% end %>

<h3>New Issue</h3>

<%= form_for @issue, url: {controller: "issue_management", action: :create}, builder: MyFormBuilder, html: {multipart: true, class: "form-horizontal", role: 'form'} do |form| %>
	<%= render partial: 'issues/form', locals: {form: form} %>
<% end %>

app/views/issue_management/show.html.erb
<% content_for :title do %>
	Showing Issue
<% end %>

<% content_for :breadcrumb do %>
	<li><%= link_to "Issue Management", issue_management_index_path %></li>
  	<li class='active'><%= @issue.name %></li>
<% end %>

<h4>Showing the issue management more detail</h4>

<div class='form-horizontal'>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>Name</label>
		<div class='col-sm-10'>
			<p class='form-control-static'><%= @issue.name %></p>
		</div>
	</div>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>Review Date</label>
		<div class='col-sm-10'>
			<% if @issue.review_date %>
				<p class='form-control-static'>
				<% if @issue.review_date < Time.now %>
					was <%= distance_of_time_in_words @issue.review_date, Time.now %> ago Review Today!
				<% else %>
					In <%=  distance_of_time_in_words @issue.review_date, Time.now %>
				<% end %>
				</p>
			<% end %>
		</div>
	</div>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>User</label>
		<div class='col-sm-10'>
			<% if @issue.user %>
				<p class='form-control-static'><%= @issue.user.name %></p>
			<% end %>
		</div>
	</div>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>Publish State</label>
		<div class='col-sm-10 form-control-static'>
			<%= @issue.state %>
		</div>
	</div>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>Options</label>
		<div class='col-sm-10'>
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		    Options <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu">
				<li><%= link_to "View", issue_management_view_path(@issue) %></li>
				<li><%= link_to "Edit", edit_issue_management_path(@issue) %></li>
				<!-- <li class="divider"></li> -->
				<li><%#= link_to "Edit Workarounds", edit_workaround_issue_management_path(@issue) %></li>
				<li><%#= link_to "Edit Solutions", edit_solutions_issue_management_path(@issue) %></li>
				<li class="divider"></li>
				<li><%= link_to "Delete", issue_path(@issue), method: :delete, data: {confirm: "Are you sure you want to Delete"} %></li>
		  </ul>
		</div>
	</div>
	<div class='form-group'>
		<label class='col-sm-2 control-label'>Publish Options</label>
		<div class='col-sm-10'>
			<% if @issue.draft? %>
					<%= link_to "To Review", draft_to_review_issue_path(@issue), class: "btn btn-default" %>
				<% elsif @issue.review? %>
					<%= link_to "To Draft", review_to_draft_issue_path(@issue), class: "btn btn-default" %>
					<%= link_to "To Publish", review_to_publish_issue_path(@issue), class: "btn btn-default" %>
					
				<% elsif @issue.publish? %>
					<%= link_to "To Draft", publish_to_draft_issue_path(@issue), class: "btn btn-default" %>
					<%= link_to "To Review", publish_to_review_issue_path(@issue), class: "btn btn-default" %>
				<% end %>
		</div>
	</div>
</div>

app/views/issue_management/view.html.erb
<%#= render partial: 'issues/show_review_table', locals: {list: @issue_workarounds} %>