config/routes.rb
Rails.application.routes.draw do
  resources :problems do
  end
  resources :problem_issue
  resources :processareas

  resources :lineups

  get "/c/:location/:machine_code" => "complaints#show", as: :indiv_show_complaint
  get "/complaints/all" => "complaints#all"
 get "/pages/:page" => "pages#show"
  

  resources :images
  resources :complaints
  get 'a/image_management' => 'images#manindex', as: :image_management

  get "/api/get_images" => 'images#get_images', as: :get_images_json

  devise_for :users

  post "/api/login" => 'json_sessions#create'
  delete "/api/logout" => 'json_sessions#destroy'

  match "issues", to: "issues#index", via: [:options]
  match "issues/:issue_id/issue_workarounds/:id", to: "issue_workarounds#cors", via: [:options]

  root :to => 'issues#index'

  get "/about" => 'static_pages#about', as: :static_about
  get "/why" => 'static_pages#why', as: :static_why
  get "/products" => 'static_pages#products', as: :static_products

  get "/home" => 'static_pages#home', as: :home
  get '/layout' => 'layouts_show#show', as: :layouts_show

  get 'assignment/show/:role_id' => 'assignments#show', as: :assignment_role_view

  namespace :jobs do
    resources :jobs
    resources :steps
  end

  scope "/admin" do
    get "/", to: "admin#index", as: "admin_index"
    get "users", to: "admin#users", as: "admin_user_static"

    get "business", to: 'admin_business#edit', as: "business_edit"
    put "businesses/:id(.:format)", to: "admin_business#update", as: "business_update"

    get "depareas/departments", to: "admin#departments", as: "admin_departments_static"
    get "depareas/areas", to: "admin#areas", as: "admin_areas_static"
    get "depareas/department_areas", to: "admin#department_areas", as: "admin_department_areas_static"
    resources :users, only: [:new, :create, :update, :destroy, :edit, :show]

    resources :admin

    resources :issue_management do
      get 'view', as: :view
      member do
        get 'show_workarounds', as: :show_workarounds
        get 'show_solutions', as: :show_solutions
        get 'show_steps', as: :show_steps

        

      end
      resources :issue_workarounds, controller: 'review_management', type: 'IssueWorkaround', u: 'workaround'
      resources :solutions, controller: 'review_management', type: 'Solution', u: 'solutions'
    end

    resources :department_areas do
      resources :locations
    end

    resources :departments
    resources :areas
    resources :department_areas
    resources :impacts
  end

  get '/profile' => 'users#profile', as: :profile

  resources :businesses do
    member do
      get 'newly_created', as: :newly_created
    end
  end

 

  

  get "/activities" => "notifications#activity_feed", as: :activity_feed
  get "/notifications" => "notifications#notification", as: :notification_feed

  get '/issues/search' => "issues#search", as: :issue_search
  get 'search_results' => "issues#search_results", as: :search_results

  resources :issues do
    member do
      get 'show_workarounds' => "reviews#index", type: 'IssueWorkaround', u: 'workarounds', as: :show_workarounds
      get 'show_solutions' => "reviews#index", type: 'Solution', u: 'solutions', as: :show_solutions
      get 'show_steps' => "detailed_steps#index", as: :show_steps
      get 'show_images', as: :show_images
      get 'history', as: :history
      get 'draft_to_review', as: :draft_to_review
      get 'review_to_draft', as: :review_to_draft
      get 'review_to_publish', as: :review_to_publish
      get 'publish_to_review', as: :publish_to_review
      get 'publish_to_draft', as: :publish_to_draft
      get 'edit/images' => "issues#edit_images", as: :edit_images
      get 'edit/workarounds' => "issues#edit_workaround", as: :edit_workaround
      get 'edit/solutions' => "issues#edit_solutions", as: :edit_solutions
      get 'edit/attempted_solutions' => "issues#edit_attempted_solutions", as: :edit_attempted_solutions
    end
    resources :detailed_steps do
      collection do
        post 'step_number_update'
        get 'quick_show'
      end
    end
    resources :notes do
      post 'mark_as_checked', as: :marked_as_checked
      post 'mark_as_user_read', as: :mark_as_user_read
    end
    resources :records, only: [:create, :index, :new]
    resources :solutions, controller: 'reviews', type: 'Solution', u: 'solutions' do
    end
    resources :issue_workarounds, controller: 'reviews', type: 'IssueWorkaround', u: 'workarounds' do
    end
  end

  resources :media, only: [:show, :new, :create, :destroy]

end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  authorize_resource
  before_action :set_lineup, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @lineups = Lineup.all
    respond_with(@lineups)
  end

  def show
    respond_with(@lineup)
  end

  def new
    @lineup = Lineup.new
    respond_with(@lineup)
  end

  def edit
  end

  def create
    @lineup = Lineup.new(lineup_params)
    @lineup.save
    respond_with(@lineup)
  end

  def update
    @lineup.update(lineup_params)
    respond_with(@lineup)
  end

  def destroy
    @lineup.destroy
    respond_with(@lineup)
  end

  private
    def set_lineup
      @lineup = Lineup.find(params[:id])
    end

    def lineup_params
      params.require(:lineup).permit(:position_number, :job_number, :master_spec, :machine, :cust_name)
    end
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/views/lineups/_form.html.erb
<%= form_for(@lineup) do |f| %>
  <% if @lineup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineup.errors.count, "error") %> prohibited this lineup from being saved:</h2>

      <ul>
      <% @lineup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position_number %><br>
    <%= f.number_field :position_number %>
  </div>
  <div class="field">
    <%= f.label :job_number %><br>
    <%= f.text_field :job_number %>
  </div>
  <div class="field">
    <%= f.label :master_spec %><br>
    <%= f.text_field :master_spec %>
  </div>
  <div class="field">
    <%= f.label :machine %><br>
    <%= f.text_field :machine %>
  </div>
    <div class="field">
    <%= f.label :cust_name %><br>
    <%= f.text_field :cust_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineups/edit.html.erb
<h1>Editing lineup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineup %> |
<%= link_to 'Back', lineups_path %>

app/views/lineups/index.html.erb
<h1>Listing lineups</h1>

<table>
  <thead>
    <tr>
      <th>Position number</th>
      <th>Job number</th>
      <th>Master spec</th>
      <th>Machine</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lineups.each do |lineup| %>
      <tr>
        <td><%= lineup.position_number %></td>
        <td><%= lineup.job_number %></td>
        <td><%= lineup.master_spec %></td>
        <td><%= lineup.machine %></td>
        <td><%= link_to 'Show', lineup %></td>
        <td><%= link_to 'Edit', edit_lineup_path(lineup) %></td>
        <td><%= link_to 'Destroy', lineup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineup', new_lineup_path %>

app/views/lineups/new.html.erb
<h1>New lineup</h1>

<%= render 'form' %>

<%= link_to 'Back', lineups_path %>

app/views/lineups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position number:</strong>
  <%= @lineup.position_number %>
</p>

<p>
  <strong>Job number:</strong>
  <%= @lineup.job_number %>
</p>

<p>
  <strong>Master spec:</strong>
  <%= @lineup.master_spec %>
</p>

<p>
  <strong>Machine:</strong>
  <%= @lineup.machine %>
</p>

<%= link_to 'Edit', edit_lineup_path(@lineup) %> |
<%= link_to 'Back', lineups_path %>